name: Push and Scan GitHub Container Registry Image

on:
  workflow_dispatch:  # 手動トリガーイベント

env:
  # 環境変数の設定
  REPO_NAME_DOCKER: kong/kong-gateway           # DockerHubのリポジトリ名
  IMAGE_TAG_DOCKER: 3.4.3.18                   # DockerHubのタグ名
  REPO_NAME_GHCR: kong-gateway  # GitHub Container Registryのリポジトリ名（小文字に変更）
  IMAGE_TAG_GHCR: 3.4.3.18                     # GHCRのタグ名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        id: login-ghcr
        run: |
          set -x
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull ARM64 Docker image
        run: |
          set -x
          # ARM64用のイメージをプル
          docker pull --platform linux/arm64 ${{ env.REPO_NAME_DOCKER }}:${{ env.IMAGE_TAG_DOCKER }}
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "Repository Owner: $REPO_OWNER_LOWER"
          # ARM64イメージにタグを付ける（--platformフラグなし）
          docker tag ${{ env.REPO_NAME_DOCKER }}:${{ env.IMAGE_TAG_DOCKER }} ghcr.io/$REPO_OWNER_LOWER/${{ env.REPO_NAME_GHCR }}:${{ env.IMAGE_TAG_GHCR }}

      - name: Push ARM64 Docker image to GitHub Container Registry
        run: |
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          # ARM64用のイメージをプッシュ
          docker push ghcr.io/$REPO_OWNER_LOWER/${{ env.REPO_NAME_GHCR }}:${{ env.IMAGE_TAG_GHCR }}

      - name: Verify architecture of pushed image
        run: |
          set -x
          # プッシュしたイメージをGitHub Container Registryからプルしてアーキテクチャを確認
          docker pull ghcr.io/$REPO_OWNER_LOWER/${{ env.REPO_NAME_GHCR }}:${{ env.IMAGE_TAG_GHCR }}
          # イメージのアーキテクチャを確認
          ARCH=$(docker inspect --format '{{.Architecture}}' ghcr.io/$REPO_OWNER_LOWER/${{ env.REPO_NAME_GHCR }}:${{ env.IMAGE_TAG_GHCR }})
          echo "Image architecture is: $ARCH"
          if [[ "$ARCH" != "arm64" ]]; then
            echo "Error: The image is not ARM64 architecture!" && exit 1
          fi
          echo "The image is ARM64 architecture."

      - name: Start GitHub Container Registry image scan (GHCR only supports GitHub Advanced Security scanning)
        run: |
          echo "Simulating image scan..."
          sleep 10  # Placeholder for actual scan

      - name: Check scan results (simulated)
        run: |
          echo "No critical vulnerabilities found." > scan-results.json
          cat scan-results.json

      - name: Upload scan results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: scan-results.json
